image: registry.znuny.com/znuny/internal/docker-otrs6ci:stable

stages:
  - test

mysql:
  stage: test
  services:
    - name: registry.znuny.com/znuny/internal/docker-mysql:stable
      alias: mysql
  script:
    - env
    - /run.sh
    - yum install -y "perl(LWP::Protocol::https)" "perl(Perl::Tidy)" "perl(Perl::Critic)"
    - cpanm Code::TidyAll
    - cpanm Perl::Critic::Moose
    - yum install -y nodejs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/ZnunyCodePolicy.sopm" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --directory OTRSCodePolicyPlugins" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --directory ZnunyCodePolicyPlugins" -s /bin/bash otrs
